### ISSUE TITLE
get_public_result does not seem to work, is it for private APIs only?

### ISSUE THREAD

**Issue by falcorocks** [PayloadSecurity/VxAPI#16]
https://www.hybrid-analysis.com/sample/4ee52e663e351af9bc2aa9bd368564ac8723131d72c3be068bf70e6814a27b53?environmentId=100 contains a report for the file I'm investigating.

I want to have this in JSON, so I'm trying to use the APIs.

`get_scan` gives me back maybe 5% of the info compared to the web report.

I then tried to use `get_public_result`, but this gives back an error that does not make sense: 

> Response status code: 200
Message:
API error has occurred. HTTP code: 200, API error code: -1, message: 'Can't find requested file.'

Here's the full request and response:
```
falco$ python3 vxapi.py get_public_result 4ee52e663e351af9bc2aa9bd368564ac8723131d72c3be068bf70e6814a27b53 -v

<<< Running 'VxWebService Python API Connector' in version '1.0.10' >>>


<<< API Limits for used API Key >>>

Webservice API usage limits: {'minute': 5, 'hour': 200}
Current API usage: {"minute": 1, "hour": 18}
Is limit reached: No

<<< Used API Key >>>

API Key: REDACTED
Auth Level: restricted
User: REDACTED

<<< Request was sent at 2017-10-05 15:36:34 >>>

Endpoint URL: https://www.hybrid-analysis.com/api/result-public/4ee52e663e351af9bc2aa9bd368564ac8723131d72c3be068bf70e6814a27b53
HTTP Method: GET
Sent GET params: {'environmentId': None, 'type': 'bin'}
Sent POST params: {}
Sent files: {}

<<< Received response at 2017-10-05 15:36:35 >>>

Response status code: 200
Message: API error has occurred. HTTP code: 200, API error code: -1, message: 'Can't find requested file.'

<<< Showing response >>>

Error has occurred and your files were not saved.
```

**Comment by millerjkd** [comment]
I'm afraid that the proprietary JSON reports are not available to the restricted API.

**Comment by kkochanski** [comment]
Hello @falcorocks 

> I then tried to use get_public_result, but this gives back an error that does not make sense:

In your request, you were pointing sample not properly. As report has `environmentId` - `https://www.hybrid-analysis.com/sample/4ee52e663e351af9bc2aa9bd368564ac8723131d72c3be068bf70e6814a27b53?environmentId=100`, it should be also given in command. So valid command will look like that: 
```
python3 vxapi.py get_public_result 4ee52e663e351af9bc2aa9bd368564ac8723131d72c3be068bf70e6814a27b53 -env 100 -v
```

Btw. `get_public_result` action got more options in the newest version of VxApi - 1.0.11.

**Comment by falcorocks** [comment]
@millerjkd I wish that was written somewhere, instead of "trial and error"ing on all the APIs. 
The error message does not give any indication of that:
`Message: API error has occurred. HTTP code: 200, API error code: -1, message: 'Can't find requested file.'`

**Comment by falcorocks** [comment]
@kkochanski thanks, it actually worked.
FYI though, the argument -env is still mentioned as optional in the latest version. I will open another issue so you guys can address it :)
