### ISSUE TITLE
	Error code: 404, returned when uploading

### ISSUE THREAD

**Issue by cyberblackghost** [PayloadSecurity/VxAPI#18]
submitURL: https://www.hybrid-analysis.com/submit
2017-10-14 21:45:09,273 - CORE - INFO - 
res: <Response [404]>
	Error code: 404, returned when uploading: c:\test\rufus-2.16.exe
2017-10-14 21:45:14,275 - CORE - INFO - 
	New file found: rufus-2.16.exe

Process finished with exit code 1

**Comment by seifreed** [comment]
HI @cyberblackghost 

The default API key doesn't allow to automatically send files over our webservice

**Comment by cyberblackghost** [comment]
Thank you all

Just update the web site so everybody know that

Thank you


[logo1withqmasters]

Menachem Tauman  |  Co Founder & CEO
Security Integration & Cyber Consulting
M: +972-52-2757707
menachemt@qmasters.co<mailto:menachemt@qmasters.co>
www.qmasters.co<http://www.qmasters.co>
