### ISSUE TITLE
not all option are available 

### ISSUE THREAD

**Issue by cyberblackghost** [PayloadSecurity/VxAPI#19]
![error](https://user-images.githubusercontent.com/32812202/31583775-deaeface-b1a9-11e7-9c2e-9c0c0c4255a9.PNG)

**Comment by kkochanski** [comment]
Hello @cyberblackghost,

`not all option are available` - do you want to say that our API is providing more actions that were listed in your command output, but they are not available?

**Comment by cyberblackghost** [comment]
HI

On the website as you can see on the picture 1 there is a lot of options

When I run it on my computer picture 2


[Alt text]



[cid:image002.png@01D345BC.F5AC8A10]

[logo1withqmasters]

Menachem Tauman  |  Co Founder & CEO
Security Integration & Cyber Consulting
M: +972-52-2757707
menachemt@qmasters.co<mailto:menachemt@qmasters.co>
www.qmasters.co<http://www.qmasters.co>

**Comment by kkochanski** [comment]
Ok. The point is that some of endpoints require different API Key privileges(in that case available are `default` and `restricted`). Before showing options, we're checking your API Key auth level, to ensure that we will show only that options which are available for given API Key. That's the reason why your view is different from the screen which is on the webpage. You are using `restricted` API Key, but webpage screen was done while using the `default` one.

I think that it will be good to update wiki a little bit, to make that case more clear.
Btw. if you're interested in obtaining `default` API Key, please contact our support by contact page in [www.payload-security.com/contact](https://www.payload-security.com/contact)

**Comment by seifreed** [comment]
Hi @cyberblackghost 

The endpoint API is prepared to work with on premise versions (Paid, commercial users) and also with our free webservice.

Depending on the API you are using (All the users at Hybrid Analysis have default API key, a restricted one)

So, the script automatically depending on your API key will show the options available.

**Comment by cyberblackghost** [comment]
OK

So what you saying on the free version it is very limited and only the payed version give you all the options

Thank you

[logo1withqmasters]

Menachem Tauman  |  Co Founder & CEO
Security Integration & Cyber Consulting
M: +972-52-2757707
menachemt@qmasters.co<mailto:menachemt@qmasters.co>
www.qmasters.co<http://www.qmasters.co>

**Comment by cyberblackghost** [comment]
Can you please send me your contact I want to speak with you


Thank you

[logo1withqmasters]

Menachem Tauman  |  Co Founder & CEO
Security Integration & Cyber Consulting
M: +972-52-2757707
menachemt@qmasters.co<mailto:menachemt@qmasters.co>
www.qmasters.co<http://www.qmasters.co>
