### ISSUE TITLE
Add support for additional options for submit_file?

### ISSUE THREAD

**Issue by datorr2** [PayloadSecurity/VxAPI#23]
The following options are available through the GUI, but not through the VxAPI:

* Runtime action script
* Runtime duration
* Custom commandline
* Custom date/time
* * Enable Hybrid Analysis
* * Enable Experimental Anti-Evasion
* * Enable Script Logging
* * Allow Input Sample Tampering
* * Route Network Traffic via TOR
* E-Mail notification
* Do not share sample with community

If this is already possible via the API, but not through VxAPI.py, I haven't been able to find any documentation that says so.

**Comment by millerjkd** [comment]
It is. Can you please E-Mail development@hybrid-analysis.com and we will get back to you.
