### ISSUE TITLE
Incorrect error when config.py is missing

### ISSUE THREAD

**Issue by u99d88** [PayloadSecurity/VxAPI#24]
`if os.path.exists('config.py'):
           ...
        else:
            raise MissingConfigurationError('Configuration is missing. Before running CLI, please copy the file \'config_tpl.pl\' from current dir, rename it to \'config.pl\', and fill')`

The error mention 'config.pl' instead of 'config.py', and so 'config_tpl.pl'.
(line 110)

**Comment by kkochanski** [comment]
Thanks for reporting. Fixed in 9e041569f71fb74ee4eab5d62cccc892ee6d1063
