### ISSUE TITLE
Incorrect API key secret

### ISSUE THREAD

**Issue by inigma117** [PayloadSecurity/VxAPI#33]
I cloned the VxAPI and loaded up my config information based on the readme file. I get this error
```
Message: 'Can't retrieve data for given API Key 'some_api_key_here' in the webservice: 'https://www.hybrid-analysis.com'. Response status code: '403'. Response message: 'incorrect API key secret''.
```

The API key secret is supposed to be deprecated in API v2 based on the my understanding of the documents.

**Comment by kkochanski** [comment]
Hi @inigma117,

Currently VxApi is only supporting API v1 so the API key with it secret is still needed. Documentation for that API version is available [here](https://www.hybrid-analysis.com/apikeys/info)

**Comment by kkochanski** [comment]
When you will re-generate/create the key in your profile page, you will see the API key with it secret. 
![image](https://user-images.githubusercontent.com/8296936/42994176-998d5eec-8c0d-11e8-965e-d607e6bb6265.png)

Given API key will be compatible with two API versions. In API v1 you have to also pass visible secret.
