### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by mcarpenter** [PayloadSecurity/VxAPI#36]
Two small problems with error messages from vxapi.py:

1. They are written to `stdout`.
2. They contain escape codes even when `stdout` is not a terminal.

The first can be solved by simply writing to `sys.stderr` instead. The second can be solved by calling `sys.stdout.isatty()` and acting appropriately on the result.

**Comment by kkochanski** [comment]
Hello, thanks for your comment. You're right about those two things - those changes will be implemented soon.

**Comment by mcarpenter** [comment]
Thanks! Maybe also output from `--verbose`? Otherwise it gets mixed in with the actual output when debugging.
