### ISSUE TITLE
What is this

### ISSUE THREAD

**Issue by bryancuz** [PayloadSecurity/VxAPI#39]
sembly>PAPADDINGXXPADDINGPADDINGXXPADDINGPADDINGXXPADDINGPADDINGXXPADDINGPADDINGXXPAD�0(0K0U0�0�0�011�1222e2�2�2�2�3�3�3&4}4�4�455k5�5�5�5*6�6�6�67%7n7�7�7?8_8�8�8919?9D9J9u9�9::?:E:�:�:�:;;;n;�;�;�;�;�;�;�;
<<F<�<�<�<�<�<�<=G=X=e=w=�=�=�=�=�=�=�=>>P>m>>�>�>�>????Y?^?{?�?�?�? �1090�0�0�0�0�011%171@1I1j1y1�1�1�1�1�12*2N2S2p2�2�2�2�2�233:3A3b3i3�3�3�3�34K4S4X4_4i4s4�4�4�5�5�5�5�5�5�5�5�5�5�5�5�56 6)6D6N6a6k6p6u6�6�6�6�6�6�6�6�6�6�6�6�67777$7C7K7T7Z7b7n7�7�7�7�7�7�7�7�7�7�7�7�7�7�7�78
888*8H8N8T8Z8`8f8m8t8{8�8�8�8�8�8�8�8�8�8�8�8�8�8�8�8�8999959<9�9�9�9�9�9�9�9�9�9�9
::T:Y:z::�:H;M;_;};�;�;�;<<.<{<�<�<�<�<�<===C=K=V=\=b=h=n=t=z=�=�=�=0 �0�01,101l;p;�;�;<,<0<P(00 0$0(0`0d0h0l0p0t0x0|0�0�0

**Comment by kkochanski** [comment]
Hello @bryancuz, while reporting an issue please attach as much information as you can (e.g. called action etc.) Can you add more details?

**Comment by kkochanski** [comment]
Closing due to missing activity.
