### ISSUE TITLE
Add API Collection:Postman

### ISSUE THREAD

**Issue by l0n3R4n93r** [PayloadSecurity/VxAPI#43]
Hello Dev's

Currently working on Automation on Malware Analysis and their supportive methods for achieving fully automation using CrowdStrike Falcon Sandbox/Hybrid Analysis.

Hoping we can add Developer API Collection for Postman.

I'm working on full fledged api collection and document in Postman, can it possible, to add here for other devs in future reference

**Comment by kkochanski** [comment]
Hello,

That repository contains a Python CLI wrapper of CrowdStrike Falcon Sandbox API. I think that it won't be a perfect place for putting Postman API Collection exactly here. I would suggest adding it to separated repository (you can create one if you would like to) and then I will mention about it in the Readme of this project.
