### ISSUE TITLE
Possible high level API?

### ISSUE THREAD

**Issue by maverickvn360** [PayloadSecurity/VxAPI#45]
Hello team,
This might sound naïve, but is it possible to convert this cli to a set of high level api calls (on top of the APIv2 and instead of using os call/exec modules) - where this module would check authorization, perform requests, summarize responses etc.?

Thanks

**Comment by kkochanski** [comment]
Hey @maverickvn360,

I'm worried that it won't be very practical for many users. In current form, everyone can use it - CLI is a common interface. While it would be converted to the requested form, the group of recipients would be tied to only Python language.

Though feel free to take a code from that application and use it in your own high-level implementation. 

Cheers

**Comment by maverickvn360** [comment]
Thanks, Cheers!
