### ISSUE TITLE
How do you get the job id if you submit it online via hybrid-analysis.com?

### ISSUE THREAD

**Issue by davebeiler** [PayloadSecurity/VxAPI#49]
trying to download a full report.... via api

**Comment by davebeiler** [comment]
im trying to get the report so that i can use the skyler tool from crowdstrike... nowhere in the tool does it say how to get the json files from the hybryid analysis

**Comment by oldkingcone** [comment]
hybrid also submits to VT when any malware is submitted. If your hash shows up on VT assume it was pushed into hybrid.

**Comment by kkochanski** [comment]
@oldkingcone , samples are not submitted to VT.
