### ISSUE TITLE
API stopped working altogether

### ISSUE THREAD

**Issue by barismutan** [PayloadSecurity/VxAPI#50]
Greetings, since last week I have not been able to fetch any result from using the API. I believe this is due to the changes on server side issues ( I have been getting the error below when I try to use the API from [https://www.hybrid-analysis.com/docs/api/v2](url).
`Resolver error at paths./search/hashes.post.responses.200.schema.items.properties.crowdstrike_ai.$ref
Could not resolve reference: #/definitions/CrowdStrikeAi
Resolver error at paths./search/hashes.post.responses.200.schema.items.properties.processes.items.properties.amsi_calls.items.$ref
Could not resolve reference: #/definitions/AmsiCall`

Are you aware of this issue? Is there anything I can to do help with the Python connnector?

**Comment by barismutan** [comment]
In the last week, I have not been able to get almost any results either using the API from the website or the Python connector. API calls from both [https://www.hybrid-analysis.com/docs/api/v2](https://www.hybrid-analysis.com/docs/api/v2) and the Python connector have been returning HTTP 520 error code most of the time and in the times that it returns a regular 200 OK response; it is tens of times slower than it used to be (a single search_hash call taking longer than 30 seconds or so.)

For your information, I have a valid API key with available quota, and another friend of mine with a vetted account API key has been experiencing the same problem.

**Comment by kkochanski** [comment]
Tomorrow you can expect fix for that. I will ping you back once it will be there. 

Cheers!

**Comment by barismutan** [comment]
Thank you so much, have a good one !

**Comment by kkochanski** [comment]
@barismutan, it has been fixed. The timings came back to normal. Cheers!
